#!/bin/sh

commit_msg_file=$1
commit_msg=$(cat "$commit_msg_file")

# Don't change it.
pattern="^\[(기능|버그|리팩토링|형식|문서|테스트)\]( [A-Z]+-\d+)? : .+$"

if ! echo "$commit_msg" | grep -qE "$pattern"; then
    echo "\033[0;31m============================================================\033[0m"
    echo "\033[0;31mError\033[0m: 커밋 메시지가 컨벤션 따르지 않습니다."
    echo "\033[0;34mExpected format\033[0m: [<목적>] {Jira} : <주제>"
    echo "\033[0;32m - 목적\033[0m: '기능, 버그, 리팩토링, 형식, 문서, 테스트'입니다."
    echo "\033[0;32m - Jira\033[0m: 선택 사항으로 Jira 티켓을 입력하세요."
    echo "\033[0;32m - 주제\033[0m: 커밋 메세지를 입력하세요."
    echo "\033[0;33mExample\033[0m: [문서] : README.md의 내용을 최신화한다"
    echo "\033[0;33mExample\033[0m: [기능] DS-1 : LUT 알고리즘을 적용한다"
    echo "\033[0;31m============================================================\033[0m"
    exit 1
fi